---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - bind-utils
    - vim
    - unzip

- name: Create Vault group {{ vault_group }}
  ansible.builtin.group:
    name: "{{ vault_group }}"
    gid: 1024

- name: Create Vault user {{ vault_user }}
  ansible.builtin.user:
    name: "{{ vault_user }}"
    comment: "User for Vault"
    uid: 1024
    group: "{{ vault_group }}"

- name: Add {{ vault_user }} to sudo in sudoers file (temporarily during dev phase)
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ vault_user }}"
    line: "{{ vault_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: yes
    validate: "/usr/sbin/visudo visudo -cf %s"

- name: Make sure includedir is present in sudoers (# does not mean comment)
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Add SSH key to authorized keys file
  ansible.posix.authorized_key:
    user: "{{ vault_user }}"
    key: "{{ lookup('file', '../../../{{ ansible_ssh_public_key_file }}') }}"
    state: present

- name: Disable password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify:
    - Restart ssh

- name: Disable root login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - Restart ssh

- name: Disable SELinux
  ansible.builtin.selinux:
    state: disabled
  notify:
    - Reboot system
